### ISSUE TITLE
Craft 3.4 + preview targets

### ISSUE THREAD

**Issue by dennisfrank** [michaelhue/craft-breakpoint#2]
## Description

Breakpoint seems to be currently not compatible with Craft 3.4:

- The preview target select of Craft is missing in the live preview
- Only when Breakpoint is activated in the live preview, the preview target select will be displayed over the responsive settings of Breakpoint

Craft 3.4:
![image](https://user-images.githubusercontent.com/65968/73985686-24a6d480-493c-11ea-91c7-6c95632251f6.png)

Craft 3.3:
![image](https://user-images.githubusercontent.com/65968/73986114-1c9b6480-493d-11ea-86e1-92cc9eeab9cf.png)

## To Reproduce

1. Open a live preview of an entry with multiple preview targets
2. The preview target select is missing above preview
3. Now activate Breakpoint
4. The preview target overlays Breakpoint’s settings

## Expected behavior

Craft’s preview target feature and Breakpoint are working together.

## Additional context

- Plugin version: 2.0.0
- Craft version: 3.4.4.1
- Browser and version: Chrome 79

**Comment by michaelhue** [comment]
Hi Dennis,

thank you for the report! I'm working on an update for compatibility with `3.4`, should be ready in a couple of days. Sorry for the delay.

**Comment by michaelhue** [comment]
I believe this is a problem with Craft, the behavior of the target selector is inconsistent between browsers. Firefox shows the target selector correctly above the Iframe, Chrome does not.

I added an issue to the Craft repo: https://github.com/craftcms/cms/issues/5616

**Comment by dennisfrank** [comment]
Thank you @michaelhue! 

Und schöne Grüße nach Hannover 😄

**Comment by michaelhue** [comment]
Turns out somebody else already opened an issue about this, check https://github.com/craftcms/cms/issues/5547. Hope it will be fixed soon, closing this for now.

Schöne Grüße zurück nach Braunschweig! :)
