### ISSUE TITLE
Error loading Settings screen

### ISSUE THREAD

**Issue by benatleith** [michaelhue/craft-breakpoint#3]
## Description

The Settings screen is inaccessible, with error:

Calling unknown method: yii\base\DynamicModel::validatePreset()

It looks as if this is due to a regression in EachValidator with custom validation, described initially here:
https://github.com/yiisoft/yii2/issues/18051

I guess there's not much that can be done until Craft updates Yii to v2.0.36 ?

## To Reproduce

1. Install the plugin
2. Visit /admin/settings/plugins/breakpoint

## Expected behavior

Settings screen operable.

## Additional context

- Plugin version: 2.0.0
- Craft version: 3.4.30
- Browser and version: Chrome 84.0.4147.105 (OSX)

**Comment by michaelhue** [comment]
Thanks for the bug report and sorry for the late reply. I'll look into it!

**Comment by michaelhue** [comment]
Please update to the latest version. The bug should be fixed now.
Thanks again for the detailed report!

**Comment by benatleith** [comment]
Awesome, thanks @michaelhue 👍
